"""30.01.2025 14:15

Revision ID: 0de862d55b1e
Revises: 
Create Date: 2025-01-30 14:16:34.932142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de862d55b1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('basket_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('basket_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price_per_piece', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_on_basket',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_basket', sa.Integer(), nullable=False),
    sa.Column('marked_for_order', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.basket_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'basket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_on_basket')
    op.drop_table('product')
    op.drop_table('basket')
    # ### end Alembic commands ###
